module CodeMirror where

import Import
import Control.Arrow
import Yesod.Core (Route)

import Data.Map (Map)
import qualified Data.Map as M

codeMirrorMode :: String -> Maybe (Route App)
codeMirrorMode = flip M.lookup codeMirrorModes

codeMirrorModes :: Map String (Route App)
codeMirrorModes = M.fromList . map (second StaticR) $
  [ ("apl", codemirror_mode_apl_apl_js)
  , ("asterisk", codemirror_mode_asterisk_asterisk_js)
  , ("clike", codemirror_mode_clike_clike_js)
  , ("clojure", codemirror_mode_clojure_clojure_js)
  , ("cobol", codemirror_mode_cobol_cobol_js)
  , ("coffeescript", codemirror_mode_coffeescript_coffeescript_js)
  , ("commonlisp", codemirror_mode_commonlisp_commonlisp_js)
  , ("css", codemirror_mode_css_css_js)
  , ("d", codemirror_mode_d_d_js)
  , ("diff", codemirror_mode_diff_diff_js)
  , ("dtd", codemirror_mode_dtd_dtd_js)
  , ("ecl", codemirror_mode_ecl_ecl_js)
  , ("eiffel", codemirror_mode_eiffel_eiffel_js)
  , ("erlang", codemirror_mode_erlang_erlang_js)
  , ("fortran", codemirror_mode_fortran_fortran_js)
  , ("gas", codemirror_mode_gas_gas_js)
  , ("gfm", codemirror_mode_gfm_gfm_js)
  , ("gherkin", codemirror_mode_gherkin_gherkin_js)
  , ("go", codemirror_mode_go_go_js)
  , ("groovy", codemirror_mode_groovy_groovy_js)
  , ("haml", codemirror_mode_haml_haml_js)
  , ("haskell", codemirror_mode_haskell_haskell_js)
  , ("haxe", codemirror_mode_haxe_haxe_js)
  , ("htmlembedded", codemirror_mode_htmlembedded_htmlembedded_js)
  , ("htmlmixed", codemirror_mode_htmlmixed_htmlmixed_js)
  , ("http", codemirror_mode_http_http_js)
  , ("jade", codemirror_mode_jade_jade_js)
  , ("javascript", codemirror_mode_javascript_javascript_js)
  , ("jinja2", codemirror_mode_jinja2_jinja2_js)
  , ("julia", codemirror_mode_julia_julia_js)
  , ("less", codemirror_mode_less_less_js)
  , ("livescript", codemirror_mode_livescript_livescript_js)
  , ("lua", codemirror_mode_lua_lua_js)
  , ("markdown", codemirror_mode_markdown_markdown_js)
  , ("mirc", codemirror_mode_mirc_mirc_js)
  , ("nginx", codemirror_mode_nginx_nginx_js)
  , ("ntriples", codemirror_mode_ntriples_ntriples_js)
  , ("ocaml", codemirror_mode_ocaml_ocaml_js)
  , ("octave", codemirror_mode_octave_octave_js)
  , ("pascal", codemirror_mode_pascal_pascal_js)
  , ("pegjs", codemirror_mode_pegjs_pegjs_js)
  , ("perl", codemirror_mode_perl_perl_js)
  , ("php", codemirror_mode_php_php_js)
  , ("pig", codemirror_mode_pig_pig_js)
  , ("properties", codemirror_mode_properties_properties_js)
  , ("python", codemirror_mode_python_python_js)
  , ("q", codemirror_mode_q_q_js)
  , ("r", codemirror_mode_r_r_js)
  , ("rst", codemirror_mode_rst_rst_js)
  , ("ruby", codemirror_mode_ruby_ruby_js)
  , ("rust", codemirror_mode_rust_rust_js)
  , ("sass", codemirror_mode_sass_sass_js)
  , ("scheme", codemirror_mode_scheme_scheme_js)
  , ("shell", codemirror_mode_shell_shell_js)
  , ("sieve", codemirror_mode_sieve_sieve_js)
  , ("smalltalk", codemirror_mode_smalltalk_smalltalk_js)
  , ("smartymixed", codemirror_mode_smartymixed_smartymixed_js)
  , ("smarty", codemirror_mode_smarty_smarty_js)
  , ("sparql", codemirror_mode_sparql_sparql_js)
  , ("sql", codemirror_mode_sql_sql_js)
  , ("stex", codemirror_mode_stex_stex_js)
  , ("tcl", codemirror_mode_tcl_tcl_js)
  , ("tiddlywiki", codemirror_mode_tiddlywiki_tiddlywiki_js)
  , ("tiki", codemirror_mode_tiki_tiki_js)
  , ("toml", codemirror_mode_toml_toml_js)
  , ("turtle", codemirror_mode_turtle_turtle_js)
  , ("vbscript", codemirror_mode_vbscript_vbscript_js)
  , ("vb", codemirror_mode_vb_vb_js)
  , ("velocity", codemirror_mode_velocity_velocity_js)
  , ("verilog", codemirror_mode_verilog_verilog_js)
  , ("xml", codemirror_mode_xml_xml_js)
  , ("xquery", codemirror_mode_xquery_xquery_js)
  , ("yaml", codemirror_mode_yaml_yaml_js)
  , ("z80", codemirror_mode_z80_z80_js)
  ]
