Hello: Hello

MenuAdmin: Admin
MenuProblems: Problems
MenuSubmits: Submits
MenuAbout: About
MenuLogout: Log out
MenuLogin: Log in

AdminTitle: Admin's page
AdminSubtitle: (admin)
AdminText: Here be some admin tools.

CoursesTitle: Courses
CourseNo: No.
CourseName: Course name
CourseRepo: A repository containing course materials.

NoCourses: There are not courses yet.
StartNewCourse: Start a new course? 

AboutTitle: About trass
AboutText: trass is an assignment submission system.
