Hello: Hello

HomeText: The Rigorous Assignment Submission System
ViewCourses: View courses
SignIn: Sign in

LoginTitle: Sign in
LoginGoogle: Login via Google
LoginGoogleText: If you already have a Google account, just sign in with it.
LoginBrowserIdText: You can sign in using your e-mail via Mozilla Persona.

MenuAdmin: Admin
MenuCourses: Courses
MenuProblems: Problems
MenuSubmits: Submits
MenuAbout: About
MenuLanguage: Language
MenuLogout: Log out
MenuLogin: Log in

AdminTitle: Admin's page
AdminSubtitle: (admin)
AdminText: Here be some admin tools.

CoursesTitle: Courses
CoursesText count@Int: You have #{show count} #{plural count "course" "courses"}.
CourseNo: No.
CourseName: Course name
CourseRepo: Course repository
CourseRepoName: Course repository name

StartNewCourse: New course
StartNewCourseQuestion: Start a new course? 
NoCourses: There are no courses yet.
NewCourseTitle: Starting a new course
NewCourseSubmit: Start course

ProblemsText count@Int: This course has #{show count} #{plural count "problem" "problems"}.
ProblemTitle: Problem title

SubmitSolution: Submit solution

NoDescription: No description.
NoTitle: No title
NoProblems: There no problems in this course yet.

AboutTitle: About trass
AboutText: trass is an assignment submission system.
