Hello: Hello

MenuAdmin: Admin
MenuProblems: Problems
MenuSubmits: Submits
MenuAbout: About
MenuLogout: Log out
MenuLogin: Log in

AdminTitle: Admin's page
AdminSubtitle: (admin)
AdminText: Here be some admin tools.

CoursesTitle: Courses
CourseNo: No.
CourseName: Course name
CourseRepo: Course repository
CourseRepoName: Course repository name

NoCourses: There are not courses yet.
StartNewCourse: Start a new course? 
NewCourseTitle: Starting a new course
NewCourseSubmit: Start course

AboutTitle: About trass
AboutText: trass is an assignment submission system.
