Hello: Привет

MenuAdmin: Админка
MenuCourses: Курсы
MenuProblems: Задачи
MenuSubmits: Посылки
MenuAbout: О trass
MenuLogout: Выйти
MenuLogin: Войти

AdminTitle: Аднимистрирование
AdminSubtitle: (администратор)
AdminText: Here be some admin tools.

CoursesTitle: Курсы
CoursesText count@Int: Доступно #{show count} #{plural count "курс" "курсы"}.
CourseNo: №
CourseName: Наименование курса
CourseRepo: Репозиторий курса
CourseRepoName: Название репозитория

StartNewCourse: Добавить курс
StartNewCourseQuestion: Начать новый курс? 
NoCourses: Пока не начато ни одного курса.
NewCourseTitle: Создание нового курса
NewCourseSubmit: Начать курс

NoDescription: Описание отсутствует.

AboutTitle: О trass
AboutText: trass это автоматическая система приёма заданий.
