HomeText: Строгая система приёма заданий.
ViewCourses: Перейти к курсам
SignIn: Войти

LoginTitle: Вход в систему
LoginGoogle: Войти, используя аккаунт Google
LoginGoogleText: Если у Вас есть аккаунт Google, Вы можете войти при помощи него.
LoginBrowserIdText: Вы можете войти, используя адрес свой электронной почты, через Mozilla Persona.

MenuAdmin: Админка
MenuCourses: Курсы
MenuProblems: Задания
MenuSubmits: Посылки
MenuAbout: О trass
MenuLanguage: Язык
MenuLogout: Выйти
MenuLogin: Войти

AdminTitle: Аднимистрирование
AdminSubtitle: (администратор)
AdminText: Here be some admin tools.

CoursesTitle: Курсы
CoursesText count@Int: Доступно #{show count} #{plural_ru count "курс" "курса" "курсов"}.
CourseNo: №
CourseName: Наименование курса
CourseRepo: Репозиторий курса
CourseRepoName: Название репозитория
CourseProblems: Задания

StartNewCourse: Добавить курс
StartNewCourseQuestion: Начать новый курс? 
NoCourses: Пока не начато ни одного курса.
NewCourseTitle: Создание нового курса
NewCourseSubmit: Начать курс

ProblemsText count@Int: В этом курсе #{show count} #{plural_ru count "задание" "задания" "заданий"}.
ProblemTitle: Задание

SubmitSolution: Отослать решение

NoDescription: Описание отсутствует.
NoTitle: Название отсутствует
NoProblems: В этом курсе пока нет заданий.

AboutTitle: О trass
AboutText: trass это автоматическая система приёма заданий.
